from django.urls import path
from . import views

urlpatterns = [

    path('pais/',                 views.PaisListView.as_view(),     name='pais'),
    path('pais/create/',          views.PaisCreateView.as_view(),   name='pais_create'),
    path('pais/<int:id>/',        views.PaisRetrieveView.as_view(), name='pais'),
    path('pais/update/<int:id>', views.PaisUpdateView.as_view(),   name='pais_update'),
    path('pais/<int:id>/delete/', views.PaisDestroyView.as_view(),  name='pais_delete'),
    path('pais/combo/<int:id>',   views.PaisComboView.as_view(),    name='pais_combo'),

    path('estado/',                     views.EstadoListView.as_view(),     name='estado'),
    path('estado/create/',              views.EstadoCreateView.as_view(),   name='estado_create'),
    path('estado/<int:id>/',            views.EstadoRetrieveView.as_view(), name='estado'),
    path('estado/update/<int:id>',     views.EstadoUpdateView.as_view(),   name='estado_update'),
    path('estado/delete/<int:id>',      views.EstadoDestroyView.as_view(),  name='estado_delete'),
    path('estado/combo/<int:id>',       views.EstadoComboView.as_view(),    name='estado_combo'),

    path('ciudad/',                     views.CiudadListView.as_view(),     name='ciudad'),
    path('ciudad/create/',              views.CiudadCreateView.as_view(),   name='ciudad_create'),
    path('ciudad/<int:id>/',            views.CiudadRetrieveView.as_view(), name='ciudad'),
    path('ciudad/update/<int:id>',     views.CiudadUpdateView.as_view(),   name='ciudad_update'),
    path('ciudad/delete/<int:id>',      views.CiudadDestroyView.as_view(),  name='ciudad_delete'),
    path('ciudad/combo/<int:id>',       views.CiudadComboView.as_view(),    name='ciudad_combo'),


    # path('municipio/',                 views.MunicipioListView.as_view(),     name='municipio'),
    # path('municipio/create/',          views.MunicipioCreateView.as_view(),   name='municipio_create'),
    # path('municipio/<int:id>/',        views.MunicipioRetrieveView.as_view(), name='municipio'),
    # path('municipio/<int:id>/update/', views.MunicipioUpdateView.as_view(),   name='municipio_update'),
    # path('municipio/<int:id>/delete/', views.MunicipioDestroyView.as_view(),  name='municipio_delete'),

    # # path('parroquias/',                views.ParroquiasListView.as_view(),     name='parroquias'),
    # # path('parroquias/create/',          views.ParroquiasCreateView.as_view(),   name='parroquias_create'),
    # # path('parroquias/<int:id>/',        views.ParroquiasRetrieveView.as_view(), name='parroquias'),
    # # path('parroquias/<int:id>/update/', views.ParroquiasUpdateView.as_view(),   name='parroquias_update'),
    # # path('parroquias/<int:id>/delete/', views.ParroquiasDestroyView.as_view(),  name='parroquias_delete'),

    path('sector/',                 views.SectorListView.as_view(),     name='sector'),
    path('sector/create/',          views.SectorCreateView.as_view(),   name='sector_create'),
    path('sector/<int:id>/',        views.SectorRetrieveView.as_view(), name='sector'),
    path('sector/update/<int:id>', views.SectorUpdateView.as_view(),   name='sector_update'),
    path('sector/<int:id>/delete/', views.SectorDestroyView.as_view(),  name='sector_delete'),

    path('subSector/',                 views.SubSectorListView.as_view(),     name='subSector'),
    path('subSector/create/',          views.SubSectorCreateView.as_view(),   name='subSector_create'),
    path('subSector/<int:id>/',        views.SubSectorRetrieveView.as_view(), name='subSector'),
    path('subSector/update/<int:id>', views.SubSectorUpdateView.as_view(),   name='subSector_update'),
    path('subSector/<int:id>/delete/', views.SubSectorDestroyView.as_view(),  name='subSector_delete'),

    path('natural/',                 views.NaturalListView.as_view(),     name='natural'),
    path('natural/create/',          views.NaturalCreateView.as_view(),   name='natural_create'),
    path('natural/<int:id>/',        views.NaturalRetrieveView.as_view(), name='natural'),
    path('natural/update/<int:id>', views.NaturalUpdateView.as_view(),   name='natural_update'),
    path('natural/<int:id>/delete/', views.NaturalDestroyView.as_view(),  name='natural_delete'),
    path('natural/filter/',          views.NaturalFilterView.as_view(),   name='natural_filter'),

    path('tipoempresa/',                 views.TipoEmpresaListView.as_view(),     name='tipoempresa'),
    path('tipoempresa/create/',          views.TipoEmpresaCreateView.as_view(),   name='tipoempresa_create'),
    path('tipoempresa/<int:id>/',        views.TipoEmpresaRetrieveView.as_view(), name='tipoempresa'),
    path('tipoempresa/update/<int:id>', views.TipoEmpresaUpdateView.as_view(),   name='tipoempresa_update'),
    path('tipoempresa/<int:id>/delete/', views.TipoEmpresaDestroyView.as_view(),  name='tipoempresa_delete'),

    path('juridica/',                 views.JuridicaListView.as_view(),     name='juridica'),
    path('juridica/create/',          views.JuridicaCreateView.as_view(),   name='juridica_create'),
    path('juridica/<int:id>/',        views.JuridicaRetrieveView.as_view(), name='juridica'),
    path('juridica/<int:id>/update/', views.JuridicaUpdateView.as_view(),   name='juridica_update'),
    path('juridica/<int:id>/delete/', views.JuridicaDestroyView.as_view(),  name='juridica_delete'),

    path('accionista/',                 views.AccionistaListView.as_view(),     name='accionista'),
    path('accionista/create/',          views.AccionistaCreateView.as_view(),   name='accionista_create'),
    path('accionista/<int:id>/',        views.AccionistaRetrieveView.as_view(), name='accionista'),
    path('accionista/<int:id>/update/', views.AccionistaUpdateView.as_view(),   name='accionista_update'),
    path('accionista/<int:id>/delete/', views.AccionistaDestroyView.as_view(),  name='accionista_delete'),

    path('sucursal/',                 views.SucursalListView.as_view(),     name='accionista'),
    path('sucursal/create/',          views.SucursalCreateView.as_view(),   name='accionista_create'),
    path('sucursal/<int:id>/',        views.SucursalRetrieveView.as_view(), name='accionista'),
    path('sucursal/<int:id>/update/', views.SucursalUpdateView.as_view(),   name='accionista_update'),
    path('sucursal/<int:id>/delete/', views.SucursalDestroyView.as_view(),  name='accionista_delete'),

    path('familia/',                 views.FamiliaListView.as_view(),     name='familia'),
    path('familia/create/',          views.FamiliaCreateView.as_view(),   name='familia_create'),
    path('familia/<int:id>/',        views.FamiliaRetrieveView.as_view(), name='familia'),
    path('familia/<int:id>/update/', views.FamiliaUpdateView.as_view(),   name='familia_update'),
    path('familia/<int:id>/delete/', views.FamiliaDestroyView.as_view(),  name='familia_delete'),

    path('subfamilia/',                 views.SubFamiliaListView.as_view(),     name='subfamilia'),
    path('subfamilia/create/',          views.SubFamiliaCreateView.as_view(),   name='subfamilia_create'),
    path('subfamilia/<int:id>/',        views.SubFamiliaRetrieveView.as_view(), name='subfamilia'),
    path('subfamilia/<int:id>/update/', views.SubFamiliaUpdateView.as_view(),   name='subfamilia_update'),
    path('subfamilia/<int:id>/delete/', views.SubFamiliaDestroyView.as_view(),  name='subfamilia_delete'),

    path('zona/',                 views.ZonaListView.as_view(),     name='zona'),
    path('zona/create/',          views.ZonaCreateView.as_view(),   name='zona_create'),
    path('zona/<int:id>/',        views.ZonaRetrieveView.as_view(), name='zona'),
    path('zona/<int:id>/update/', views.ZonaUpdateView.as_view(),   name='zona_update'),
    path('zona/<int:id>/delete/', views.ZonaDestroyView.as_view(),  name='zona_delete'),

    path('vendedor/',                 views.VendedorListView.as_view(),     name='vendedor'),
    path('vendedor/create/',          views.VendedorCreateView.as_view(),   name='vendedor_create'),
    path('vendedor/<int:id>/',        views.VendedorRetrieveView.as_view(), name='vendedor'),
    path('vendedor/<int:id>/update/', views.VendedorUpdateView.as_view(),   name='vendedor_update'),
    path('vendedor/<int:id>/delete/', views.VendedorDestroyView.as_view(),  name='vendedor_delete'),

    path('ruta/',                 views.RutaListView.as_view(),     name='ruta'),
    path('ruta/create/',          views.RutaCreateView.as_view(),   name='ruta_create'),
    path('ruta/<int:id>/',        views.RutaRetrieveView.as_view(), name='ruta'),
    path('ruta/<int:id>/update/', views.RutaUpdateView.as_view(),   name='ruta_update'),
    path('ruta/<int:id>/delete/', views.RutaDestroyView.as_view(),  name='ruta_delete'),

    path('unidadmedida/',                       views.UnidadMedidaListView.as_view(),     name='unidadmedida'),
    path('unidadmedida/create/',                views.UnidadMedidaCreateView.as_view(),   name='unidadmedida_create'),
    path('unidadmedida/<int:id>/',              views.UnidadMedidaRetrieveView.as_view(), name='unidadmedida'),
    path('unidadmedida/<int:id>/update/',       views.UnidadMedidaUpdateView.as_view(),   name='unidadmedida_update'),
    path('unidadmedida/<int:id>/delete/',       views.UnidadMedidaDestroyView.as_view(),  name='unidadmedida_delete'),

    path('unidadtributaria/',                     views.UnidadTributariaListView.as_view(),     name='unidadtributaria'),
    path('unidadtributaria/create/',              views.UnidadTributariaCreateView.as_view(),   name='unidadtributaria_create'),
    path('unidadtributaria/<int:id>/',            views.UnidadTributariaRetrieveView.as_view(), name='unidadtributaria'),
    path('unidadtributaria/<int:id>/update/',     views.UnidadTributariaUpdateView.as_view(),   name='unidadtributaria_update'),
    path('unidadtributaria/<int:id>/delete/',     views.UnidadTributariaDestroyView.as_view(),  name='unidadtributaria_delete'),

    path('iva/',                             views.IvaListView.as_view(),     name='iva'),
    path('iva/create/',                      views.IvaCreateView.as_view(),   name='iva_create'),
    path('iva/<int:id>/',                    views.IvaRetrieveView.as_view(), name='iva'),
    path('iva/<int:id>/update/',             views.IvaUpdateView.as_view(),   name='iva_update'),
    path('iva/<int:id>/delete/',             views.IvaDestroyView.as_view(),  name='iva_delete'),



    # path('banco/',                 views.BancoListView.as_view(),     name='banco'),
    # path('banco/create/',          views.BancoCreateView.as_view(),   name='banco_create'),
    # path('banco/<int:id>/',        views.BancoRetrieveView.as_view(), name='banco'),
    # path('banco/<int:id>/update/', views.BancoUpdateView.as_view(),   name='banco_update'),
    # path('banco/<int:id>/delete/', views.BancoDestroyView.as_view(),  name='banco_delete'),

    # path('cuenta/',                 views.CuentaListView.as_view(),     name='cuenta'),
    # path('cuenta/create/',          views.CuentaCreateView.as_view(),   name='cuenta_create'),
    # path('cuenta/<int:id>/',        views.CuentaRetrieveView.as_view(), name='cuenta'),
    # path('cuenta/<int:id>/update/', views.CuentaUpdateView.as_view(),   name='cuenta_update'),
    # path('cuenta/<int:id>/delete/', views.CuentaDestroyView.as_view(),  name='cuenta_delete'),

    # path('agencia/',                 views.AgenciaListView.as_view(),     name='agencia'),
    # path('agencia/create/',          views.AgenciaCreateView.as_view(),   name='agencia_create'),
    # path('agencia/<int:id>/',        views.AgenciaRetrieveView.as_view(), name='agencia'),
    # path('agencia/<int:id>/update/', views.AgenciaUpdateView.as_view(),   name='agencia_update'),
    # path('agencia/<int:id>/delete/', views.AgenciaDestroyView.as_view(),  name='agencia_delete'),

    # path('articulo/',                        views.ArticuloListView.as_view(),     name='articulo'),
    # path('articulo/create/',                 views.ArticuloCreateView.as_view(),   name='articulo_create'),
    # path('articulo/<int:id>/',               views.ArticuloRetrieveView.as_view(), name='articulo'),
    # path('articulo/<int:id>/update/',        views.ArticuloUpdateView.as_view(),   name='articulo_update'),
    # path('articulo/<int:id>/delete/',        views.ArticuloDestroyView.as_view(),  name='articulo_delete'),

    # path('cmarco/',                          views.CmarcoListView.as_view(),     name='cmarco'),
    # path('cmarco/create/',                   views.CmarcoCreateView.as_view(),   name='cmarco_create'),
    # path('cmarco/<int:id>/',                 views.CmarcoRetrieveView.as_view(), name='cmarco'),
    # path('cmarco/<int:id>/update/',          views.CmarcoUpdateView.as_view(),   name='cmarco_update'),
    # path('cmarco/<int:id>/delete/',          views.CmarcoDestroyView.as_view(),  name='cmarco_delete'),

    # path('cpago/',                           views.CpagoListView.as_view(),     name='cpago'),
    # path('cpago/create/',                    views.CpagoCreateView.as_view(),   name='cpago_create'),
    # path('cpago/<int:id>/',                  views.CpagoRetrieveView.as_view(), name='cpago'),
    # path('cpago/<int:id>/update/',           views.CpagoUpdateView.as_view(),   name='cpago_update'),
    # path('cpago/<int:id>/delete/',           views.CpagoDestroyView.as_view(),  name='cpago_delete'),

    # path('fpago/',                           views.FpagoListView.as_view(),     name='fpago'),
    # path('fpago/create/',                    views.FpagoCreateView.as_view(),   name='fpago_create'),
    # path('fpago/<int:id>/',                  views.FpagoRetrieveView.as_view(), name='fpago'),
    # path('fpago/<int:id>/update/',           views.FpagoUpdateView.as_view(),   name='fpago_update'),
    # path('fpago/<int:id>/delete/',           views.FpagoDestroyView.as_view(),  name='fpago_delete'),

    # path('ginstruccion/',                    views.GinstruccionListView.as_view(),     name='ginstruccion'),
    # path('ginstruccion/create/',             views.GinstruccionCreateView.as_view(),   name='ginstruccion_create'),
    # path('ginstruccion/<int:id>/',           views.GinstruccionRetrieveView.as_view(), name='ginstruccion'),
    # path('ginstruccion/<int:id>/update/',    views.GinstruccionUpdateView.as_view(),   name='ginstruccion_update'),
    # path('ginstruccion/<int:id>/delete/',    views.GinstruccionDestroyView.as_view(),  name='ginstruccion_delete'),

    # path('monedas/',                         views.MonedasListView.as_view(),     name='monedas'),
    # path('monedas/create/',                  views.MonedasCreateView.as_view(),   name='monedas_create'),
    # path('monedas/<int:id>/',                views.MonedasRetrieveView.as_view(), name='monedas'),
    # path('monedas/<int:id>/update/',         views.MonedasUpdateView.as_view(),   name='monedas_update'),
    # path('monedas/<int:id>/delete/',         views.MonedasDestroyView.as_view(),  name='monedas_delete'),

    # path('pcontratacion/',                   views.PcontratacionListView.as_view(),     name='pcontratacion'),
    # path('pcontratacion/create/',            views.PcontratacionCreateView.as_view(),   name='pcontratacion_create'),
    # path('pcontratacion/<int:id>/',          views.PcontratacionRetrieveView.as_view(), name='pcontratacion'),
    # path('pcontratacion/<int:id>/update/',   views.PcontratacionUpdateView.as_view(),   name='pcontratacion_update'),
    # path('pcontratacion/<int:id>/delete/',   views.PcontratacionDestroyView.as_view(),  name='pcontratacion_delete'),

    # path('presupuesto/',                     views.PresupuestoListView.as_view(),     name='presupuesto'),
    # path('presupuesto/create/',              views.PresupuestoCreateView.as_view(),   name='presupuesto_create'),
    # path('presupuesto/<int:id>/',            views.PresupuestoRetrieveView.as_view(), name='presupuesto'),
    # path('presupuesto/<int:id>/update/',     views.PresupuestoUpdateView.as_view(),   name='presupuesto_update'),
    # path('presupuesto/<int:id>/delete/',     views.PresupuestoDestroyView.as_view(),  name='presupuesto_delete'),

    # path('profesiones/',                     views.ProfesionesListView.as_view(),     name='profesiones'),
    # path('profesiones/create/',              views.ProfesionesCreateView.as_view(),   name='profesiones_create'),
    # path('profesiones/<int:id>/',            views.ProfesionesRetrieveView.as_view(), name='profesiones'),
    # path('profesiones/<int:id>/update/',     views.ProfesionesUpdateView.as_view(),   name='profesiones_update'),
    # path('profesiones/<int:id>/delete/',     views.ProfesionesDestroyView.as_view(),  name='profesiones_delete'),

    # path('tclientes/',                       views.TclientesListView.as_view(),     name='tclientes'),
    # path('tclientes/create/',                views.TclientesCreateView.as_view(),   name='tclientes_create'),
    # path('tclientes/<int:id>/',              views.TclientesRetrieveView.as_view(), name='tclientes'),
    # path('tclientes/<int:id>/update/',       views.TclientesUpdateView.as_view(),   name='tclientes_update'),
    # path('tclientes/<int:id>/delete/',       views.TclientesDestroyView.as_view(),  name='tclientes_delete'),

    # path('tcomunicaciones/',                 views.TcomunicacionesListView.as_view(),     name='tcomunicaciones'),
    # path('tcomunicaciones/create/',          views.TcomunicacionesCreateView.as_view(),   name='tcomunicaciones_create'),
    # path('tcomunicaciones/<int:id>/',        views.TcomunicacionesRetrieveView.as_view(), name='tcomunicaciones'),
    # path('tcomunicaciones/<int:id>/update/', views.TcomunicacionesUpdateView.as_view(),   name='tcomunicaciones_update'),
    # path('tcomunicaciones/<int:id>/delete/', views.TcomunicacionesDestroyView.as_view(),  name='tcomunicaciones_delete'),

    # path('tempresas/',                       views.TempresasListView.as_view(),     name='tempresas'),
    # path('tempresas/create/',                views.TempresasCreateView.as_view(),   name='tempresas_create'),
    # path('tempresas/<int:id>/',              views.TempresasRetrieveView.as_view(), name='tempresas'),
    # path('tempresas/<int:id>/update/',       views.TempresasUpdateView.as_view(),   name='tempresas_update'),
    # path('tempresas/<int:id>/delete/',       views.TempresasDestroyView.as_view(),  name='tempresas_delete'),

    # path('tretenciones/',                    views.TretencionesListView.as_view(),     name='tretenciones'),
    # path('tretenciones/create/',             views.TretencionesCreateView.as_view(),   name='tretenciones_create'),
    # path('tretenciones/<int:id>/',           views.TretencionesRetrieveView.as_view(), name='tretenciones'),
    # path('tretenciones/<int:id>/update/',    views.TretencionesUpdateView.as_view(),   name='tretenciones_update'),
    # path('tretenciones/<int:id>/delete/',    views.TretencionesDestroyView.as_view(),  name='tretenciones_delete'),

    # path('waletr/',                          views.WaletrListView.as_view(),     name='waletr'),
    # path('waletr/create/',                   views.WaletrCreateView.as_view(),   name='waletr_create'),
    # path('waletr/<int:id>/',                 views.WaletrRetrieveView.as_view(), name='waletr'),
    # path('waletr/<int:id>/update/',          views.WaletrUpdateView.as_view(),   name='waletr_update'),
    # path('waletr/<int:id>/delete/',          views.WaletrDestroyView.as_view(),  name='waletr_delete'),

    #path('bien/',                 views.BienListView.as_view(),     name='bien'),
    #path('bien/create/',          views.BienCreateView.as_view(),   name='bien_create'),
    #path('bien/<int:id>/',        views.BienRetrieveView.as_view(), name='bien'),
    #path('bien/<int:id>/update/', views.BienUpdateView.as_view(),   name='bien_update'),
    #path('bien/<int:id>/delete/', views.BienDestroyView.as_view(),  name='bien_delete'),

    #path('categorias/',                 views.CategoriasListView.as_view(),     name='categorias'),
    #path('categorias/create/',          views.CategoriasCreateView.as_view(),   name='categorias_create'),
    #path('categorias/<int:id>/',        views.CategoriasRetrieveView.as_view(), name='categorias'),
    #path('categorias/<int:id>/update/', views.CategoriasUpdateView.as_view(),   name='categorias_update'),
    #path('categorias/<int:id>/delete/', views.CategoriasDestroyView.as_view(),  name='categorias_delete'),

    #path('concepto/',                 views.ConceptoListView.as_view(),     name='concepto'),
    #path('concepto/create/',          views.ConceptoCreateView.as_view(),   name='concepto_create'),
    #path('concepto/<int:id>/',        views.ConceptoRetrieveView.as_view(), name='concepto'),
    #path('concepto/<int:id>/update/', views.ConceptoUpdateView.as_view(),   name='concepto_update'),
    #path('concepto/<int:id>/delete/', views.ConceptoDestroyView.as_view(),  name='concepto_delete'),

    #path('concepto_due/',                 views.Concepto_dueListView.as_view(),     name='concepto_due'),
    #path('concepto_due/create/',          views.Concepto_dueCreateView.as_view(),   name='concepto_due_create'),
    #path('concepto_due/<int:id>/',        views.Concepto_dueRetrieveView.as_view(), name='concepto_due'),
    #path('concepto_due/<int:id>/update/', views.Concepto_dueUpdateView.as_view(),   name='concepto_due_update'),
    #path('concepto_due/<int:id>/delete/', views.Concepto_dueDestroyView.as_view(),  name='concepto_due_delete'),

    #path('detalle_ingreso/',                 views.Detalle_ingresoListView.as_view(),     name='detalle_ingreso'),
    #path('detalle_ingreso/create/',          views.Detalle_ingresoCreateView.as_view(),   name='detalle_ingreso_create'),
    #path('detalle_ingreso/<int:id>/',        views.Detalle_ingresoRetrieveView.as_view(), name='detalle_ingreso'),
    #path('detalle_ingreso/<int:id>/update/', views.Detalle_ingresoUpdateView.as_view(),   name='detalle_ingreso_update'),
    #path('detalle_ingreso/<int:id>/delete/', views.Detalle_ingresoDestroyView.as_view(),  name='detalle_ingreso_delete'),

    #path('detalle_ingreso_due/',                 views.Detalle_ingreso_dueListView.as_view(),     name='detalle_ingreso_due'),
    #path('detalle_ingreso_due/create/',          views.Detalle_ingreso_dueCreateView.as_view(),   name='detalle_ingreso_due_create'),
    #path('detalle_ingreso_due/<int:id>/',        views.Detalle_ingreso_dueRetrieveView.as_view(), name='detalle_ingreso_due'),
    #path('detalle_ingreso_due/<int:id>/update/', views.Detalle_ingreso_dueUpdateView.as_view(),   name='detalle_ingreso_due_update'),
    #path('detalle_ingreso_due/<int:id>/delete/', views.Detalle_ingreso_dueDestroyView.as_view(),  name='detalle_ingreso_due_delete'),

    #path('ingreso/',                 views.IngresoListView.as_view(),     name='ingreso'),
    #path('ingreso/create/',          views.IngresoCreateView.as_view(),   name='ingreso_create'),
    #path('ingreso/<int:id>/',        views.IngresoRetrieveView.as_view(), name='ingreso'),
    #path('ingreso/<int:id>/update/', views.IngresoUpdateView.as_view(),   name='ingreso_update'),
    #path('ingreso/<int:id>/delete/', views.IngresoDestroyView.as_view(),  name='ingreso_delete'),

    #path('ingreso_copia/',                 views.Ingreso_copiaListView.as_view(),     name='ingreso_copia'),
    #path('ingreso_copia/create/',          views.Ingreso_copiaCreateView.as_view(),   name='ingreso_copia_create'),
    #path('ingreso_copia/<int:id>/',        views.Ingreso_copiaRetrieveView.as_view(), name='ingreso_copia'),
    #path('ingreso_copia/<int:id>/update/', views.Ingreso_copiaUpdateView.as_view(),   name='ingreso_copia_update'),
    #path('ingreso_copia/<int:id>/delete/', views.Ingreso_copiaDestroyView.as_view(),  name='ingreso_copia_delete'),

    #path('ingreso_due/',                 views.Ingreso_dueListView.as_view(),     name='ingreso_due'),
    #path('ingreso_due/create/',          views.Ingreso_dueCreateView.as_view(),   name='ingreso_due_create'),
    #path('ingreso_due/<int:id>/',        views.Ingreso_dueRetrieveView.as_view(), name='ingreso_due'),
    #path('ingreso_due/<int:id>/update/', views.Ingreso_dueUpdateView.as_view(),   name='ingreso_due_update'),
    #path('ingreso_due/<int:id>/delete/', views.Ingreso_dueDestroyView.as_view(),  name='ingreso_due_delete'),

    #path('libro_tesoreria/',                 views.Libro_tesoreriaListView.as_view(),     name='libro_tesoreria'),
    #path('libro_tesoreria/create/',          views.Libro_tesoreriaCreateView.as_view(),   name='libro_tesoreria_create'),
    #path('libro_tesoreria/<int:id>/',        views.Libro_tesoreriaRetrieveView.as_view(), name='libro_tesoreria'),
    #path('libro_tesoreria/<int:id>/update/', views.Libro_tesoreriaUpdateView.as_view(),   name='libro_tesoreria_update'),
    #path('libro_tesoreria/<int:id>/delete/', views.Libro_tesoreriaDestroyView.as_view(),  name='libro_tesoreria_delete'),

    #path('acce_dgte/',                 views.Acce_dgteListView.as_view(),     name='acce_dgte'),
    #path('acce_dgte/create/',          views.Acce_dgteCreateView.as_view(),   name='acce_dgte_create'),
    #path('acce_dgte/<int:id>/',        views.Acce_dgteRetrieveView.as_view(), name='acce_dgte'),
    #path('acce_dgte/<int:id>/update/', views.Acce_dgteUpdateView.as_view(),   name='acce_dgte_update'),
    #path('acce_dgte/<int:id>/delete/', views.Acce_dgteDestroyView.as_view(),  name='acce_dgte_delete'),

    #path('acpa_dcco/',                 views.Acpa_dccoListView.as_view(),     name='acpa_dcco'),
    #path('acpa_dcco/create/',          views.Acpa_dccoCreateView.as_view(),   name='acpa_dcco_create'),
    #path('acpa_dcco/<int:id>/',        views.Acpa_dccoRetrieveView.as_view(), name='acpa_dcco'),
    #path('acpa_dcco/<int:id>/update/', views.Acpa_dccoUpdateView.as_view(),   name='acpa_dcco_update'),
    #path('acpa_dcco/<int:id>/delete/', views.Acpa_dccoDestroyView.as_view(),  name='acpa_dcco_delete'),

    #path('cubi_deco/',                 views.Cubi_decoListView.as_view(),     name='cubi_deco'),
    #path('cubi_deco/create/',          views.Cubi_decoCreateView.as_view(),   name='cubi_deco_create'),
    #path('cubi_deco/<int:id>/',        views.Cubi_decoRetrieveView.as_view(), name='cubi_deco'),
    #path('cubi_deco/<int:id>/update/', views.Cubi_decoUpdateView.as_view(),   name='cubi_deco_update'),
    #path('cubi_deco/<int:id>/delete/', views.Cubi_decoDestroyView.as_view(),  name='cubi_deco_delete'),

    #path('deus_dgco/',                 views.Deus_dgcoListView.as_view(),     name='deus_dgco'),
    #path('deus_dgco/create/',          views.Deus_dgcoCreateView.as_view(),   name='deus_dgco_create'),
    #path('deus_dgco/<int:id>/',        views.Deus_dgcoRetrieveView.as_view(), name='deus_dgco'),
    #path('deus_dgco/<int:id>/update/', views.Deus_dgcoUpdateView.as_view(),   name='deus_dgco_update'),
    #path('deus_dgco/<int:id>/delete/', views.Deus_dgcoDestroyView.as_view(),  name='deus_dgco_delete'),

    #path('enfi_dgte/',                 views.Enfi_dgteListView.as_view(),     name='enfi_dgte'),
    #path('enfi_dgte/create/',          views.Enfi_dgteCreateView.as_view(),   name='enfi_dgte_create'),
    #path('enfi_dgte/<int:id>/',        views.Enfi_dgteRetrieveView.as_view(), name='enfi_dgte'),
    #path('enfi_dgte/<int:id>/update/', views.Enfi_dgteUpdateView.as_view(),   name='enfi_dgte_update'),
    #path('enfi_dgte/<int:id>/delete/', views.Enfi_dgteDestroyView.as_view(),  name='enfi_dgte_delete'),

    #path('esta_dcco/',                 views.Esta_dccoListView.as_view(),     name='esta_dcco'),
    #path('esta_dcco/create/',          views.Esta_dccoCreateView.as_view(),   name='esta_dcco_create'),
    #path('esta_dcco/<int:id>/',        views.Esta_dccoRetrieveView.as_view(), name='esta_dcco'),
    #path('esta_dcco/<int:id>/update/', views.Esta_dccoUpdateView.as_view(),   name='esta_dcco_update'),
    #path('esta_dcco/<int:id>/delete/', views.Esta_dccoDestroyView.as_view(),  name='esta_dcco_delete'),

    #path('form_dgte/',                 views.Form_dgteListView.as_view(),     name='form_dgte'),
    #path('form_dgte/create/',          views.Form_dgteCreateView.as_view(),   name='form_dgte_create'),
    #path('form_dgte/<int:id>/',        views.Form_dgteRetrieveView.as_view(), name='form_dgte'),
    #path('form_dgte/<int:id>/update/', views.Form_dgteUpdateView.as_view(),   name='form_dgte_update'),
    #path('form_dgte/<int:id>/delete/', views.Form_dgteDestroyView.as_view(),  name='form_dgte_delete'),

    #path('inmueble/',                 views.InmuebleListView.as_view(),     name='inmueble'),
    #path('inmueble/create/',          views.InmuebleCreateView.as_view(),   name='inmueble_create'),
    #path('inmueble/<int:id>/',        views.InmuebleRetrieveView.as_view(), name='inmueble'),
    #path('inmueble/<int:id>/update/', views.InmuebleUpdateView.as_view(),   name='inmueble_update'),
    #path('inmueble/<int:id>/delete/', views.InmuebleDestroyView.as_view(),  name='inmueble_delete'),

    #path('mete_dgte/',                 views.Mete_dgteListView.as_view(),     name='mete_dgte'),
    #path('mete_dgte/create/',          views.Mete_dgteCreateView.as_view(),   name='mete_dgte_create'),
    #path('mete_dgte/<int:id>/',        views.Mete_dgteRetrieveView.as_view(), name='mete_dgte'),
    #path('mete_dgte/<int:id>/update/', views.Mete_dgteUpdateView.as_view(),   name='mete_dgte_update'),
    #path('mete_dgte/<int:id>/delete/', views.Mete_dgteDestroyView.as_view(),  name='mete_dgte_delete'),

    #path('otda_dcco/',                 views.Otda_dccoListView.as_view(),     name='otda_dcco'),
    #path('otda_dcco/create/',          views.Otda_dccoCreateView.as_view(),   name='otda_dcco_create'),
    #path('otda_dcco/<int:id>/',        views.Otda_dccoRetrieveView.as_view(), name='otda_dcco'),
    #path('otda_dcco/<int:id>/update/', views.Otda_dccoUpdateView.as_view(),   name='otda_dcco_update'),
    #path('otda_dcco/<int:id>/delete/', views.Otda_dccoDestroyView.as_view(),  name='otda_dcco_delete'),

    #path('repr_dgco/',                 views.Repr_dgcoListView.as_view(),     name='repr_dgco'),
    #path('repr_dgco/create/',          views.Repr_dgcoCreateView.as_view(),   name='repr_dgco_create'),
    #path('repr_dgco/<int:id>/',        views.Repr_dgcoRetrieveView.as_view(), name='repr_dgco'),
    #path('repr_dgco/<int:id>/update/', views.Repr_dgcoUpdateView.as_view(),   name='repr_dgco_update'),
    #path('repr_dgco/<int:id>/delete/', views.Repr_dgcoDestroyView.as_view(),  name='repr_dgco_delete'),

    #path('repr_dgte/',                 views.Repr_dgteListView.as_view(),     name='repr_dgte'),
    #path('repr_dgte/create/',          views.Repr_dgteCreateView.as_view(),   name='repr_dgte_create'),
    #path('repr_dgte/<int:id>/',        views.Repr_dgteRetrieveView.as_view(), name='repr_dgte'),
    #path('repr_dgte/<int:id>/update/', views.Repr_dgteUpdateView.as_view(),   name='repr_dgte_update'),
    #path('repr_dgte/<int:id>/delete/', views.Repr_dgteDestroyView.as_view(),  name='repr_dgte_delete'),

    #path('sepu_dgte/',                 views.Sepu_dgteListView.as_view(),     name='sepu_dgte'),
    #path('sepu_dgte/create/',          views.Sepu_dgteCreateView.as_view(),   name='sepu_dgte_create'),
    #path('sepu_dgte/<int:id>/',        views.Sepu_dgteRetrieveView.as_view(), name='sepu_dgte'),
    #path('sepu_dgte/<int:id>/update/', views.Sepu_dgteUpdateView.as_view(),   name='sepu_dgte_update'),
    #path('sepu_dgte/<int:id>/delete/', views.Sepu_dgteDestroyView.as_view(),  name='sepu_dgte_delete'),

    #path('sopo_deco/',                 views.Sopo_decoListView.as_view(),     name='sopo_deco'),
    #path('sopo_deco/create/',          views.Sopo_decoCreateView.as_view(),   name='sopo_deco_create'),
    #path('sopo_deco/<int:id>/',        views.Sopo_decoRetrieveView.as_view(), name='sopo_deco'),
    #path('sopo_deco/<int:id>/update/', views.Sopo_decoUpdateView.as_view(),   name='sopo_deco_update'),
    #path('sopo_deco/<int:id>/delete/', views.Sopo_decoDestroyView.as_view(),  name='sopo_deco_delete'),

    #path('tech_deco/',                 views.Tech_decoListView.as_view(),     name='tech_deco'),
    #path('tech_deco/create/',          views.Tech_decoCreateView.as_view(),   name='tech_deco_create'),
    #path('tech_deco/<int:id>/',        views.Tech_decoRetrieveView.as_view(), name='tech_deco'),
    #path('tech_deco/<int:id>/update/', views.Tech_decoUpdateView.as_view(),   name='tech_deco_update'),
    #path('tech_deco/<int:id>/delete/', views.Tech_decoDestroyView.as_view(),  name='tech_deco_delete'),

    #path('teco_dgco/',                 views.Teco_dgcoListView.as_view(),     name='teco_dgco'),
    #path('teco_dgco/create/',          views.Teco_dgcoCreateView.as_view(),   name='teco_dgco_create'),
    #path('teco_dgco/<int:id>/',        views.Teco_dgcoRetrieveView.as_view(), name='teco_dgco'),
    #path('teco_dgco/<int:id>/update/', views.Teco_dgcoUpdateView.as_view(),   name='teco_dgco_update'),
    #path('teco_dgco/<int:id>/delete/', views.Teco_dgcoDestroyView.as_view(),  name='teco_dgco_delete'),

    #path('tete_dgte/',                 views.Tete_dgteListView.as_view(),     name='tete_dgte'),
    #path('tete_dgte/create/',          views.Tete_dgteCreateView.as_view(),   name='tete_dgte_create'),
    #path('tete_dgte/<int:id>/',        views.Tete_dgteRetrieveView.as_view(), name='tete_dgte'),
    #path('tete_dgte/<int:id>/update/', views.Tete_dgteUpdateView.as_view(),   name='tete_dgte_update'),
    #path('tete_dgte/<int:id>/delete/', views.Tete_dgteDestroyView.as_view(),  name='tete_dgte_delete'),

    #path('tipa_dcco/',                 views.Tipa_dccoListView.as_view(),     name='tipa_dcco'),
    #path('tipa_dcco/create/',          views.Tipa_dccoCreateView.as_view(),   name='tipa_dcco_create'),
    #path('tipa_dcco/<int:id>/',        views.Tipa_dccoRetrieveView.as_view(), name='tipa_dcco'),
    #path('tipa_dcco/<int:id>/update/', views.Tipa_dccoUpdateView.as_view(),   name='tipa_dcco_update'),
    #path('tipa_dcco/<int:id>/delete/', views.Tipa_dccoDestroyView.as_view(),  name='tipa_dcco_delete'),

    #path('tipo_dgco/',                 views.Tipo_dgcoListView.as_view(),     name='tipo_dgco'),
    #path('tipo_dgco/create/',          views.Tipo_dgcoCreateView.as_view(),   name='tipo_dgco_create'),
    #path('tipo_dgco/<int:id>/',        views.Tipo_dgcoRetrieveView.as_view(), name='tipo_dgco'),
    #path('tipo_dgco/<int:id>/update/', views.Tipo_dgcoUpdateView.as_view(),   name='tipo_dgco_update'),
    #path('tipo_dgco/<int:id>/delete/', views.Tipo_dgcoDestroyView.as_view(),  name='tipo_dgco_delete'),

    #path('topo_dgte/',                 views.Topo_dgteListView.as_view(),     name='topo_dgte'),
    #path('topo_dgte/create/',          views.Topo_dgteCreateView.as_view(),   name='topo_dgte_create'),
    #path('topo_dgte/<int:id>/',        views.Topo_dgteRetrieveView.as_view(), name='topo_dgte'),
    #path('topo_dgte/<int:id>/update/', views.Topo_dgteUpdateView.as_view(),   name='topo_dgte_update'),
    #path('topo_dgte/<int:id>/delete/', views.Topo_dgteDestroyView.as_view(),  name='topo_dgte_delete'),

    #path('ubic_dgte/',                 views.Ubic_dgteListView.as_view(),     name='ubic_dgte'),
    #path('ubic_dgte/create/',          views.Ubic_dgteCreateView.as_view(),   name='ubic_dgte_create'),
    #path('ubic_dgte/<int:id>/',        views.Ubic_dgteRetrieveView.as_view(), name='ubic_dgte'),
    #path('ubic_dgte/<int:id>/update/', views.Ubic_dgteUpdateView.as_view(),   name='ubic_dgte_update'),
    #path('ubic_dgte/<int:id>/delete/', views.Ubic_dgteDestroyView.as_view(),  name='ubic_dgte_delete'),

    #path('usac_dgte/',                 views.Usac_dgteListView.as_view(),     name='usac_dgte'),
    #path('usac_dgte/create/',          views.Usac_dgteCreateView.as_view(),   name='usac_dgte_create'),
    #path('usac_dgte/<int:id>/',        views.Usac_dgteRetrieveView.as_view(), name='usac_dgte'),
    #path('usac_dgte/<int:id>/update/', views.Usac_dgteUpdateView.as_view(),   name='usac_dgte_update'),
    #path('usac_dgte/<int:id>/delete/', views.Usac_dgteDestroyView.as_view(),  name='usac_dgte_delete'),

    #path('amte_clap/',                 views.Amte_clapListView.as_view(),     name='amte_clap'),
    #path('amte_clap/create/',          views.Amte_clapCreateView.as_view(),   name='amte_clap_create'),
    #path('amte_clap/<int:id>/',        views.Amte_clapRetrieveView.as_view(), name='amte_clap'),
    #path('amte_clap/<int:id>/update/', views.Amte_clapUpdateView.as_view(),   name='amte_clap_update'),
    #path('amte_clap/<int:id>/delete/', views.Amte_clapDestroyView.as_view(),  name='amte_clap_delete'),

    #path('calles/',                 views.CallesListView.as_view(),     name='calles'),
    #path('calles/create/',          views.CallesCreateView.as_view(),   name='calles_create'),
    #path('calles/<int:id>/',        views.CallesRetrieveView.as_view(), name='calles'),
    #path('calles/<int:id>/update/', views.CallesUpdateView.as_view(),   name='calles_update'),
    #path('calles/<int:id>/delete/', views.CallesDestroyView.as_view(),  name='calles_delete'),

    #path('caracter/',                 views.CaracterListView.as_view(),     name='caracter'),
    #path('caracter/create/',          views.CaracterCreateView.as_view(),   name='caracter_create'),
    #path('caracter/<int:id>/',        views.CaracterRetrieveView.as_view(), name='caracter'),
    #path('caracter/<int:id>/update/', views.CaracterUpdateView.as_view(),   name='caracter_update'),
    #path('caracter/<int:id>/delete/', views.CaracterDestroyView.as_view(),  name='caracter_delete'),

    #path('menu/',                 views.MenuListView.as_view(),     name='menu'),
    #path('menu/create/',          views.MenuCreateView.as_view(),   name='menu_create'),
    #path('menu/<int:id>/',        views.MenuRetrieveView.as_view(), name='menu'),
    #path('menu/<int:id>/update/', views.MenuUpdateView.as_view(),   name='menu_update'),
    #path('menu/<int:id>/delete/', views.MenuDestroyView.as_view(),  name='menu_delete'),

    #path('menu_f/',                 views.Menu_fListView.as_view(),     name='menu_f'),
    #path('menu_f/create/',          views.Menu_fCreateView.as_view(),   name='menu_f_create'),
    #path('menu_f/<int:id>/',        views.Menu_fRetrieveView.as_view(), name='menu_f'),
    #path('menu_f/<int:id>/update/', views.Menu_fUpdateView.as_view(),   name='menu_f_update'),
    #path('menu_f/<int:id>/delete/', views.Menu_fDestroyView.as_view(),  name='menu_f_delete'),


    #path('operador/',                 views.OperadorListView.as_view(),     name='operador'),
    #path('operador/create/',          views.OperadorCreateView.as_view(),   name='operador_create'),
    #path('operador/<int:id>/',        views.OperadorRetrieveView.as_view(), name='operador'),
    #path('operador/<int:id>/update/', views.OperadorUpdateView.as_view(),   name='operador_update'),
    #path('operador/<int:id>/delete/', views.OperadorDestroyView.as_view(),  name='operador_delete'),

    #path('operador_c/',                 views.Operador_cListView.as_view(),     name='operador_c'),
    #path('operador_c/create/',          views.Operador_cCreateView.as_view(),   name='operador_c_create'),
    #path('operador_c/<int:id>/',        views.Operador_cRetrieveView.as_view(), name='operador_c'),
    #path('operador_c/<int:id>/update/', views.Operador_cUpdateView.as_view(),   name='operador_c_update'),
    #path('operador_c/<int:id>/delete/', views.Operador_cDestroyView.as_view(),  name='operador_c_delete'),

    #path('operador_f/',                 views.Operador_fListView.as_view(),     name='operador_f'),
    #path('operador_f/create/',          views.Operador_fCreateView.as_view(),   name='operador_f_create'),
    #path('operador_f/<int:id>/',        views.Operador_fRetrieveView.as_view(), name='operador_f'),
    #path('operador_f/<int:id>/update/', views.Operador_fUpdateView.as_view(),   name='operador_f_update'),
    #path('operador_f/<int:id>/delete/', views.Operador_fDestroyView.as_view(),  name='operador_f_delete'),

    #path('organizacion/',                 views.OrganizacionListView.as_view(),     name='organizacion'),
    #path('organizacion/create/',          views.OrganizacionCreateView.as_view(),   name='organizacion_create'),
    #path('organizacion/<int:id>/',        views.OrganizacionRetrieveView.as_view(), name='organizacion'),
    #path('organizacion/<int:id>/update/', views.OrganizacionUpdateView.as_view(),   name='organizacion_update'),
    #path('organizacion/<int:id>/delete/', views.OrganizacionDestroyView.as_view(),  name='organizacion_delete'),




    #path('varios/',                 views.VariosListView.as_view(),     name='varios'),
    #path('varios/create/',          views.VariosCreateView.as_view(),   name='varios_create'),
    #path('varios/<int:id>/',        views.VariosRetrieveView.as_view(), name='varios'),
    #path('varios/<int:id>/update/', views.VariosUpdateView.as_view(),   name='varios_update'),
    #path('varios/<int:id>/delete/', views.VariosDestroyView.as_view(),  name='varios_delete'),



    #path('censo_vehiculos/',                 views.Censo_vehiculosListView.as_view(),     name='censo_vehiculos'),
    #path('censo_vehiculos/create/',          views.Censo_vehiculosCreateView.as_view(),   name='censo_vehiculos_create'),
    #path('censo_vehiculos/<int:id>/',        views.Censo_vehiculosRetrieveView.as_view(), name='censo_vehiculos'),
    #path('censo_vehiculos/<int:id>/update/', views.Censo_vehiculosUpdateView.as_view(),   name='censo_vehiculos_update'),
    #path('censo_vehiculos/<int:id>/delete/', views.Censo_vehiculosDestroyView.as_view(),  name='censo_vehiculos_delete'),

    #path('centros_votacion/',                 views.Centros_votacionListView.as_view(),     name='centros_votacion'),
    #path('centros_votacion/create/',          views.Centros_votacionCreateView.as_view(),   name='centros_votacion_create'),
    #path('centros_votacion/<int:id>/',        views.Centros_votacionRetrieveView.as_view(), name='centros_votacion'),
    #path('centros_votacion/<int:id>/update/', views.Centros_votacionUpdateView.as_view(),   name='centros_votacion_update'),
    #path('centros_votacion/<int:id>/delete/', views.Centros_votacionDestroyView.as_view(),  name='centros_votacion_delete'),

    #path('clap/',                 views.ClapListView.as_view(),     name='clap'),
    #path('clap/create/',          views.ClapCreateView.as_view(),   name='clap_create'),
    #path('clap/<int:id>/',        views.ClapRetrieveView.as_view(), name='clap'),
    #path('clap/<int:id>/update/', views.ClapUpdateView.as_view(),   name='clap_update'),
    #path('clap/<int:id>/delete/', views.ClapDestroyView.as_view(),  name='clap_delete'),

    #path('libro_rojo/',                 views.Libro_rojoListView.as_view(),     name='libro_rojo'),
    #path('libro_rojo/create/',          views.Libro_rojoCreateView.as_view(),   name='libro_rojo_create'),
    #path('libro_rojo/<int:id>/',        views.Libro_rojoRetrieveView.as_view(), name='libro_rojo'),
    #path('libro_rojo/<int:id>/update/', views.Libro_rojoUpdateView.as_view(),   name='libro_rojo_update'),
    #path('libro_rojo/<int:id>/delete/', views.Libro_rojoDestroyView.as_view(),  name='libro_rojo_delete'),

    #path('listado_gasolina/',                 views.Listado_gasolinaListView.as_view(),     name='listado_gasolina'),
    #path('listado_gasolina/create/',          views.Listado_gasolinaCreateView.as_view(),   name='listado_gasolina_create'),
    #path('listado_gasolina/<int:id>/',        views.Listado_gasolinaRetrieveView.as_view(), name='listado_gasolina'),
    #path('listado_gasolina/<int:id>/update/', views.Listado_gasolinaUpdateView.as_view(),   name='listado_gasolina_update'),
    #path('listado_gasolina/<int:id>/delete/', views.Listado_gasolinaDestroyView.as_view(),  name='listado_gasolina_delete'),

    #path('ras/',                 views.RasListView.as_view(),     name='ras'),
    #path('ras/create/',          views.RasCreateView.as_view(),   name='ras_create'),
    #path('ras/<int:id>/',        views.RasRetrieveView.as_view(), name='ras'),
    #path('ras/<int:id>/update/', views.RasUpdateView.as_view(),   name='ras_update'),
    #path('ras/<int:id>/delete/', views.RasDestroyView.as_view(),  name='ras_delete'),

    #path('rep/',                 views.RepListView.as_view(),     name='rep'),
    #path('rep/create/',          views.RepCreateView.as_view(),   name='rep_create'),
    #path('rep/<int:id>/',        views.RepRetrieveView.as_view(), name='rep'),
    #path('rep/<int:id>/update/', views.RepUpdateView.as_view(),   name='rep_update'),
    #path('rep/<int:id>/delete/', views.RepDestroyView.as_view(),  name='rep_delete'),

    #path('saime/',                 views.SaimeListView.as_view(),     name='saime'),
    #path('saime/create/',          views.SaimeCreateView.as_view(),   name='saime_create'),
    #path('saime/<int:id>/',        views.SaimeRetrieveView.as_view(), name='saime'),
    #path('saime/<int:id>/update/', views.SaimeUpdateView.as_view(),   name='saime_update'),
    #path('saime/<int:id>/delete/', views.SaimeDestroyView.as_view(),  name='saime_delete'),

    #path('juntamunicipal/',                 views.JuntamunicipalListView.as_view(),     name='juntamunicipal'),
    #path('juntamunicipal/create/',          views.JuntamunicipalCreateView.as_view(),   name='juntamunicipal_create'),
    #path('juntamunicipal/<int:id>/',        views.JuntamunicipalRetrieveView.as_view(), name='juntamunicipal'),
    #path('juntamunicipal/<int:id>/update/', views.JuntamunicipalUpdateView.as_view(),   name='juntamunicipal_update'),
    #path('juntamunicipal/<int:id>/delete/', views.JuntamunicipalDestroyView.as_view(),  name='juntamunicipal_delete'),

    #path('patr_wilmar/',                 views.Patr_wilmarListView.as_view(),     name='patr_wilmar'),
    #path('patr_wilmar/create/',          views.Patr_wilmarCreateView.as_view(),   name='patr_wilmar_create'),
    #path('patr_wilmar/<int:id>/',        views.Patr_wilmarRetrieveView.as_view(), name='patr_wilmar'),
    #path('patr_wilmar/<int:id>/update/', views.Patr_wilmarUpdateView.as_view(),   name='patr_wilmar_update'),
    #path('patr_wilmar/<int:id>/delete/', views.Patr_wilmarDestroyView.as_view(),  name='patr_wilmar_delete'),

    #path('patrol_d/',                 views.Patrol_dListView.as_view(),     name='patrol_d'),
    #path('patrol_d/create/',          views.Patrol_dCreateView.as_view(),   name='patrol_d_create'),
    #path('patrol_d/<int:id>/',        views.Patrol_dRetrieveView.as_view(), name='patrol_d'),
    #path('patrol_d/<int:id>/update/', views.Patrol_dUpdateView.as_view(),   name='patrol_d_update'),
    #path('patrol_d/<int:id>/delete/', views.Patrol_dDestroyView.as_view(),  name='patrol_d_delete'),

    #path('patrol_m/',                 views.Patrol_mListView.as_view(),     name='patrol_m'),
    #path('patrol_m/create/',          views.Patrol_mCreateView.as_view(),   name='patrol_m_create'),
    #path('patrol_m/<int:id>/',        views.Patrol_mRetrieveView.as_view(), name='patrol_m'),
    #path('patrol_m/<int:id>/update/', views.Patrol_mUpdateView.as_view(),   name='patrol_m_update'),
    #path('patrol_m/<int:id>/delete/', views.Patrol_mDestroyView.as_view(),  name='patrol_m_delete'),

    #path('patrullados/',                 views.PatrulladosListView.as_view(),     name='patrullados'),
    #path('patrullados/create/',          views.PatrulladosCreateView.as_view(),   name='patrullados_create'),
    #path('patrullados/<int:id>/',        views.PatrulladosRetrieveView.as_view(), name='patrullados'),
    #path('patrullados/<int:id>/update/', views.PatrulladosUpdateView.as_view(),   name='patrullados_update'),
    #path('patrullados/<int:id>/delete/', views.PatrulladosDestroyView.as_view(),  name='patrullados_delete'),

    #path('patrullados_1433/',                 views.Patrullados_1433ListView.as_view(),     name='patrullados_1433'),
    #path('patrullados_1433/create/',          views.Patrullados_1433CreateView.as_view(),   name='patrullados_1433_create'),
    #path('patrullados_1433/<int:id>/',        views.Patrullados_1433RetrieveView.as_view(), name='patrullados_1433'),
    #path('patrullados_1433/<int:id>/update/', views.Patrullados_1433UpdateView.as_view(),   name='patrullados_1433_update'),
    #path('patrullados_1433/<int:id>/delete/', views.Patrullados_1433DestroyView.as_view(),  name='patrullados_1433_delete'),

    #path('patrullados_1521/',                 views.Patrullados_1521ListView.as_view(),     name='patrullados_1521'),
    #path('patrullados_1521/create/',          views.Patrullados_1521CreateView.as_view(),   name='patrullados_1521_create'),
    #path('patrullados_1521/<int:id>/',        views.Patrullados_1521RetrieveView.as_view(), name='patrullados_1521'),
    #path('patrullados_1521/<int:id>/update/', views.Patrullados_1521UpdateView.as_view(),   name='patrullados_1521_update'),
    #path('patrullados_1521/<int:id>/delete/', views.Patrullados_1521DestroyView.as_view(),  name='patrullados_1521_delete'),

    #path('patrullados_1808/',                 views.Patrullados_1808ListView.as_view(),     name='patrullados_1808'),
    #path('patrullados_1808/create/',          views.Patrullados_1808CreateView.as_view(),   name='patrullados_1808_create'),
    #path('patrullados_1808/<int:id>/',        views.Patrullados_1808RetrieveView.as_view(), name='patrullados_1808'),
    #path('patrullados_1808/<int:id>/update/', views.Patrullados_1808UpdateView.as_view(),   name='patrullados_1808_update'),
    #path('patrullados_1808/<int:id>/delete/', views.Patrullados_1808DestroyView.as_view(),  name='patrullados_1808_delete'),

    #path('patrullados_sabado/',                 views.Patrullados_sabadoListView.as_view(),     name='patrullados_sabado'),
    #path('patrullados_sabado/create/',          views.Patrullados_sabadoCreateView.as_view(),   name='patrullados_sabado_create'),
    #path('patrullados_sabado/<int:id>/',        views.Patrullados_sabadoRetrieveView.as_view(), name='patrullados_sabado'),
    #path('patrullados_sabado/<int:id>/update/', views.Patrullados_sabadoUpdateView.as_view(),   name='patrullados_sabado_update'),
    #path('patrullados_sabado/<int:id>/delete/', views.Patrullados_sabadoDestroyView.as_view(),  name='patrullados_sabado_delete'),

    #path('sufragar/',                 views.SufragarListView.as_view(),     name='sufragar'),
    #path('sufragar/create/',          views.SufragarCreateView.as_view(),   name='sufragar_create'),
    #path('sufragar/<int:id>/',        views.SufragarRetrieveView.as_view(), name='sufragar'),
    #path('sufragar/<int:id>/update/', views.SufragarUpdateView.as_view(),   name='sufragar_update'),
    #path('sufragar/<int:id>/delete/', views.SufragarDestroyView.as_view(),  name='sufragar_delete'),
]
