version: '3.8'

services:  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8082 licensing_platform.wsgi --workers=4
    volumes:
      - static_volume:/code/statictciles
    expose:
      - 8082
    env_file:
      - .env

volumes:
  .:
  static:

networks:
  default:
    external:
      name: delzam