version: '3.9'

services:  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./config/nginx/certs/:/etc/certs
    expose:
      - "443"
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: ng
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - app


volumes:
  .:
  static:

networks:
  default:
    external:
      name: delzam