version: '3.9'

services:  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    expose:
      - 8082
    env_file:
      - .env

volumes:
  .:
  static:

networks:
  default:
    external:
      name: delzam