# Generated by Django 4.0.4 on 2022-04-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0002_estado_estado_estado_id_46d099_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('nomb_ciud', models.CharField(default='', max_length=200, unique=True, verbose_name='nomb_ciud')),
                ('codi_esta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='asiam.estado')),
            ],
            options={
                'db_table': '"comun"."ciudad"',
                'ordering': ['nomb_ciud'],
            },
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['id'], name='ciudad_id_ed44a1_idx'),
        ),
    ]
