# Generated by Django 4.0.4 on 2022-04-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0003_ciudad_ciudad_ciudad_id_ed44a1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('nomb_sect', models.CharField(default='', max_length=200, unique=True, verbose_name='Nombre del Sector')),
                ('codi_ciud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad', to='asiam.ciudad')),
            ],
            options={
                'db_table': '"comun"."sector"',
                'ordering': ['nomb_sect'],
            },
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['id'], name='sector_id_de02da_idx'),
        ),
    ]
