# Generated by Django 4.0.4 on 2022-05-06 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0004_sector_sector_sector_id_de02da_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('nomb_suse', models.CharField(default='', max_length=30, unique=True, verbose_name='Nombre del Sub Sector')),
                ('codi_sect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sector', to='asiam.sector')),
            ],
            options={
                'db_table': '"comun"."subsector"',
                'ordering': ['nomb_suse'],
            },
        ),
        migrations.AddIndex(
            model_name='subsector',
            index=models.Index(fields=['id'], name='subsector_id_6cf8d2_idx'),
        ),
    ]
