# Generated by Django 4.0.4 on 2022-04-29 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0005_subsector_subsector_subsector_id_6cf8d2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('naci_pena', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Nacionalidad')),
                ('cedu_pena', models.IntegerField(default=0, unique=True, verbose_name='Cedula')),
                ('prno_pena', models.CharField(default='', max_length=50, verbose_name='Primer Nombre')),
                ('seno_pena', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('prap_pena', models.CharField(default='', max_length=50, verbose_name='Primer Apellido')),
                ('seap_pena', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('sexo_pena', models.CharField(default='', max_length=10, verbose_name='Sexo')),
                ('edoc_pena', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Estado Civil')),
                ('fena_pena', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('dire_pena', models.TextField(blank=True, default='', max_length=254, null=True, verbose_name='Direccion Habitacion')),
                ('riff_pena', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='RIF')),
                ('codi_ciud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural.codi_ciud+', to='asiam.ciudad')),
                ('codi_sect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural.codi_sect+', to='asiam.sector')),
            ],
            options={
                'db_table': '"comun"."natural"',
                'ordering': ['cedu_pena'],
            },
        ),
        migrations.AddIndex(
            model_name='natural',
            index=models.Index(fields=['id'], name='natural_id_cd1cb4_idx'),
        ),
    ]
