# Generated by Django 4.0.4 on 2022-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0006_natural_natural_natural_id_cd1cb4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_tiem', models.CharField(default='', max_length=30, unique=True, verbose_name='Descricpcion tipo de empresa')),
            ],
            options={
                'db_table': '"comun"."tipo_empresa"',
                'ordering': ['desc_tiem'],
            },
        ),
        migrations.AddIndex(
            model_name='tipoempresa',
            index=models.Index(fields=['id'], name='tipo_empres_id_745ff0_idx'),
        ),
    ]
