# Generated by Django 4.0.4 on 2022-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0008_juridica_juridica_juridica_id_26f9c5_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridica',
            name='folo_peju',
            field=models.JSONField(blank=True, null=True, verbose_name='Foto del Local'),
        ),
        migrations.AlterField(
            model_name='juridica',
            name='fori_peju',
            field=models.JSONField(blank=True, null=True, verbose_name='Foto del Rif'),
        ),
    ]
