# Generated by Django 4.0.4 on 2022-04-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0009_alter_juridica_folo_peju_alter_juridica_fori_peju'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('fere_acci', models.DateField(blank=True, verbose_name='Fecha de Registro')),
                ('codi_acci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural.codi_natu+', to='asiam.natural')),
                ('codi_juri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Juridica.codi_juri+', to='asiam.juridica')),
            ],
            options={
                'db_table': '"comun"."accionista"',
                'ordering': ['codi_acci'],
            },
        ),
        migrations.AddIndex(
            model_name='accionista',
            index=models.Index(fields=['id'], name='accionista_id_1a2e91_idx'),
        ),
    ]
