# Generated by Django 4.0.4 on 2022-05-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0011_tipocliente_tipocliente_tipo_client_id_075e6a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_fami', models.CharField(default='', max_length=200, unique=True, verbose_name='desc_fami')),
                ('abae_fami', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='abae_fami')),
                ('agru_fami', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='agru_fami')),
            ],
            options={
                'db_table': '"empr"."familia"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='familia',
            index=models.Index(fields=['id'], name='familia_id_476c59_idx'),
        ),
    ]
