# Generated by Django 4.0.4 on 2022-04-29 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0013_familia_familia_familia_id_476c59_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_sufa', models.CharField(default='', max_length=200, unique=True, verbose_name='desc_sufa')),
                ('abae_sufa', models.CharField(blank=True, default='', max_length=3, null=True, unique=True, verbose_name='abae_sufa')),
                ('agru_sufa', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='agru_sufa')),
                ('codi_fami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familia', to='asiam.familia')),
            ],
            options={
                'db_table': '"empr"."sub_familia"',
                'ordering': ['desc_sufa'],
            },
        ),
        migrations.AddIndex(
            model_name='subfamilia',
            index=models.Index(fields=['id'], name='sub_familia_id_f8eae4_idx'),
        ),
    ]
