# Generated by Django 4.0.4 on 2022-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0014_subfamilia_subfamilia_sub_familia_id_f8eae4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_zona', models.CharField(default='', max_length=200, unique=True, verbose_name='Nombre de la Zona')),
            ],
            options={
                'db_table': '"empr"."zona"',
                'ordering': ['desc_zona'],
            },
        ),
        migrations.AddIndex(
            model_name='zona',
            index=models.Index(fields=['id'], name='zona_id_b139f5_idx'),
        ),
    ]
