# Generated by Django 4.0.4 on 2022-05-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0014_zona_zona_zona_id_b139f5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('fein_vend', models.DateField(verbose_name='Fecha de Ingreso del Vendedor')),
                ('foto_vend', models.JSONField(blank=True, null=True, verbose_name='Foto del Vendedor')),
                ('codi_natu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural', to='asiam.natural')),
            ],
            options={
                'db_table': '"empr"."vendedor"',
                'ordering': ['codi_natu'],
            },
        ),
        migrations.AddIndex(
            model_name='vendedor',
            index=models.Index(fields=['id'], name='vendedor_id_5cac0b_idx'),
        ),
    ]
