# Generated by Django 4.0.4 on 2022-05-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0016_ruta_ruta_ruta_id_d46be4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_unme', models.CharField(default='', max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'db_table': '"comun"."unidad_medida"',
                'ordering': ['desc_unme'],
            },
        ),
        migrations.AddIndex(
            model_name='unidadmedida',
            index=models.Index(fields=['id'], name='unidad_medi_id_46af74_idx'),
        ),
    ]
