# Generated by Django 4.0.4 on 2022-05-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0018_iva_iva_iva_id_5f7d13_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('mont_untr', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Monto')),
                ('fini_untr', models.DateField(verbose_name='Entrada en vigencia')),
                ('ffin_untr', models.DateField(verbose_name='Final de la Vigencia')),
            ],
            options={
                'db_table': '"comun"."unidad_tributaria"',
                'ordering': ['fini_untr'],
            },
        ),
        migrations.AddIndex(
            model_name='unidadtributaria',
            index=models.Index(fields=['id'], name='unidad_trib_id_a3b68d_idx'),
        ),
    ]
