# Generated by Django 4.0.4 on 2022-05-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0019_unidadtributaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_mone', models.CharField(default='', max_length=120, unique=True, verbose_name='Descripcion de la Moenda')),
            ],
            options={
                'db_table': '"comun"."moneda"',
                'ordering': ['desc_mone'],
            },
        ),
        migrations.AddIndex(
            model_name='moneda',
            index=models.Index(fields=['id'], name='moneda_id_e8ef9d_idx'),
        ),
    ]
