# Generated by Django 4.0.4 on 2022-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0020_moneda_moneda_moneda_id_e8ef9d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='code_pais',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Codigo del Pais'),
        ),
        migrations.AddField(
            model_name='pais',
            name='dial_pais',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Prefijo Telefonico del Pais'),
        ),
        migrations.AddField(
            model_name='pais',
            name='name_pais',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nombre del Pais en Ingles'),
        ),
    ]
