# Generated by Django 4.0.4 on 2022-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0021_pais_code_pais_pais_dial_pais_pais_name_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nomb_pais',
            field=models.CharField(default='', max_length=120, unique=True, verbose_name='Nombre del Pais'),
        ),
    ]
