# Generated by Django 4.0.4 on 2022-05-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0022_alter_pais_nomb_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfamilia',
            name='abae_sufa',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='abae_sufa'),
        ),
    ]
