# Generated by Django 4.0.4 on 2022-05-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0023_alter_subfamilia_abae_sufa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfamilia',
            name='abae_sufa',
        ),
    ]
