# Generated by Django 4.0.4 on 2022-05-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0025_subfamilia_abae_sufa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subfamilia',
            options={},
        ),
        migrations.RemoveField(
            model_name='subfamilia',
            name='desc_sufa',
        ),
    ]
