# Generated by Django 4.0.4 on 2022-05-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0027_subfamilia_desc_sufa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfamilia',
            name='abae_sufa',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='abae_sufa'),
        ),
    ]
