# Generated by Django 4.0.4 on 2022-05-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0028_alter_subfamilia_abae_sufa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('codi_arti', models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Codigo del Articulo SIAE')),
                ('desc_agen', models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Nombre del Articulo')),
                ('coba_arti', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Codigo de Barras del Articulo')),
                ('cmin_arti', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Cantidad Minima')),
                ('cmax_arti', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Cantidad Maxima')),
                ('por1_arti', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de Utilidad 1 Por Articulo')),
                ('por2_arti', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de Utilidad 2 Por Articulo')),
                ('por3_arti', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de Utilidad 3 Por Articulo')),
                ('ppre_arti', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje Preferido Por Articulo')),
                ('foto_arti', models.JSONField()),
                ('exgr_arti', models.BooleanField(verbose_name='Exento Grabado del Articulo')),
                ('codc_pres', models.IntegerField(verbose_name='Codigo de Presentacion de Compra')),
                ('codv_pres', models.IntegerField(verbose_name='Codigo de Presentacion de Venta')),
                ('capc_arti', models.IntegerField(verbose_name='Capacidad de Compra del Articulo')),
                ('capv_arti', models.IntegerField(verbose_name='Capacidad de Venta del Articulo')),
                ('proc_arti', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Codigo del Articulo SIAE')),
                ('codi_ivaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Iva', to='asiam.iva')),
                ('codi_sufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_familia', to='asiam.subfamilia')),
            ],
            options={
                'db_table': '"empr"."articulo"',
                'ordering': ['desc_agen'],
            },
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['id'], name='articulo_id_abce88_idx'),
        ),
    ]
