# Generated by Django 4.0.4 on 2022-05-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0029_articulo_articulo_articulo_id_abce88_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('fein_clie', models.DateField(verbose_name='Fecha de Ingreso del Cliente')),
                ('codi_ante', models.IntegerField(blank=True, null=True, verbose_name='Codigo Anterior')),
                ('cred_clie', models.BooleanField(verbose_name='Credito del Cliente')),
                ('mocr_clie', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto del Credito')),
                ('plcr_clie', models.IntegerField(verbose_name='Plazo del del Credito')),
                ('prde_clie', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentage de Descuento')),
                ('prau_clie', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentage de Aumento')),
                ('foto_clie', models.JSONField(blank=True, null=True, verbose_name='Foto del Cliente')),
                ('codi_juri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Juridica.codi_juri+', to='asiam.juridica')),
                ('codi_natu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural.codi_natu+', to='asiam.natural')),
                ('codi_vend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor.codi_vend+', to='asiam.vendedor')),
            ],
            options={
                'db_table': '"empr"."cliente"',
                'ordering': ['codi_natu'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['id'], name='cliente_id_2e92bd_idx'),
        ),
    ]
