# Generated by Django 4.0.4 on 2022-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0030_cliente_cliente_cliente_id_2e92bd_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fein_clie',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso del Cliente'),
        ),
    ]
