# Generated by Django 4.0.4 on 2022-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0031_alter_cliente_fein_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natural',
            name='fena_pena',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
