# Generated by Django 4.0.4 on 2022-05-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0032_alter_natural_fena_pena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='natural',
            options={'ordering': ['-id']},
        ),
    ]
