# Generated by Django 4.0.4 on 2022-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0037_alter_rutadetallevendedor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_ivag', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Descripcion del Iva General')),
            ],
            options={
                'db_table': '"comun"."iva_general"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='ivageneral',
            index=models.Index(fields=['id'], name='iva_general_id_3dad8f_idx'),
        ),
    ]
