# Generated by Django 4.0.4 on 2022-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0038_ivageneral_ivageneral_iva_general_id_3dad8f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iva',
            name='alic_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Alicuota'),
        ),
    ]
