# Generated by Django 4.0.4 on 2022-06-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0040_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='exgr_arti',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Exento Grabado del Articulo'),
        ),
    ]
