# Generated by Django 4.0.4 on 2022-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0041_alter_articulo_exgr_arti'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='idae_arti',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Codigo del Articulo SIAE'),
        ),
    ]
