# Generated by Django 4.0.4 on 2022-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0042_articulo_idae_arti'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE IF EXISTS empr.articulo DROP CONSTRAINT IF EXISTS articulo_desc_agen_key"),
        migrations.AlterField(
            model_name='articulo',
            name='desc_arti',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nombre del Articulo'),
        ),
    ]
