# Generated by Django 4.0.4 on 2022-06-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0044_remove_articulo_codi_ivaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='desc_arti',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Nombre del Articulo'),
        ),
    ]
