# Generated by Django 4.0.4 on 2022-06-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0045_alter_articulo_desc_arti'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codi_ivti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ivti_general', to='asiam.ivageneral'),
        ),
    ]
