# Generated by Django 4.0.4 on 2022-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0046_articulo_codi_ivti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_pres', models.CharField(default='', max_length=200, unique=True, verbose_name='desc_pres')),
                ('tipo_pres', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='tipo_pres')),
                ('abre_pres', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='abre_pres')),
            ],
            options={
                'db_table': '"empr"."presentacion"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='presentacion',
            index=models.Index(fields=['id'], name='presentacio_id_88eafc_idx'),
        ),
    ]
