# Generated by Django 4.0.4 on 2022-06-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0048_alter_presentacion_abre_pres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codc_pres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_compra', to='asiam.presentacion'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codv_pres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_venta', to='asiam.presentacion'),
        ),
    ]
