# Generated by Django 4.0.4 on 2022-06-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0049_alter_articulo_codc_pres_alter_articulo_codv_pres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='capc_arti',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad de Compra del Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='capv_arti',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad de Venta del Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cmax_arti',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Cantidad Maxima'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cmin_arti',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Cantidad Minima'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='foto_arti',
            field=models.JSONField(blank=True, null=True, verbose_name='Foto del Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='por1_arti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Porcentaje de Utilidad 1 Por Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='por2_arti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Porcentaje de Utilidad 2 Por Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='por3_arti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Porcentaje de Utilidad 3 Por Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ppre_arti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Porcentaje Preferido Por Articulo'),
        ),
    ]
