# Generated by Django 4.0.4 on 2022-07-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0050_alter_articulo_capc_arti_alter_articulo_capv_arti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='por4_arti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Porcentaje de Utilidad 4 Por Articulo'),
        ),
    ]
