# Generated by Django 4.0.4 on 2022-07-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0051_articulo_por4_arti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('mocr_prov', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto del Credito')),
                ('plcr_prov', models.IntegerField(verbose_name='Plazo del del Credito')),
                ('foto_prov', models.JSONField(blank=True, null=True, verbose_name='Foto del Proveedor')),
                ('obse_prov', models.TextField(blank=True, null=True, verbose_name='Observaciones del Proveedor')),
                ('codi_juri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Juridica.codi_juri+', to='asiam.juridica')),
                ('codi_natu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural.codi_natu+', to='asiam.natural')),
                ('codi_repr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural.codi_natu+', to='asiam.natural')),
            ],
            options={
                'db_table': '"empr"."proveedor"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['id'], name='proveedor_id_82292a_idx'),
        ),
    ]
