# Generated by Django 4.0.4 on 2022-07-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0052_proveedor_proveedor_proveedor_id_82292a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('codi_arti_prov', models.CharField(default='', max_length=50, verbose_name='Codigo del Articulo Proveedor')),
                ('obse_arti_prov', models.TextField(blank=True, null=True, verbose_name='Observaciones del Proveedor')),
                ('codi_arti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo.id+', to='asiam.articulo')),
                ('codi_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor.codi_prov+', to='asiam.proveedor')),
            ],
            options={
                'db_table': '"empr"."articulo_proveedor"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='articuloproveedor',
            index=models.Index(fields=['id'], name='articulo_pr_id_7cc506_idx'),
        ),
    ]
