# Generated by Django 4.0.4 on 2022-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0053_articuloproveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridica',
            name='riff_peju',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='RIF'),
        ),
    ]
