# Generated by Django 4.0.4 on 2022-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0054_alter_juridica_riff_peju'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloproveedor',
            name='codi_arti_prov',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo del Articulo Proveedor'),
        ),
    ]
