# Generated by Django 4.0.4 on 2022-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0055_alter_articuloproveedor_codi_arti_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='obse_clie',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Cliente'),
        ),
    ]
