# Generated by Django 4.0.4 on 2022-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0056_cliente_obse_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codi_ante',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Codigo Anterior'),
        ),
    ]
