# Generated by Django 4.0.4 on 2022-08-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0057_alter_cliente_codi_ante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='nomb_ruta',
        ),
    ]
