# Generated by Django 4.0.4 on 2022-08-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0058_remove_ruta_nomb_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='nomb_ruta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Ruta'),
        ),
    ]
