# Generated by Django 4.0.4 on 2022-09-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0060_cliente_posi_clie_ruta_posi_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_ctco', models.CharField(default='', max_length=200, unique=True, verbose_name='Descripcion de la Categoria del Contacto')),
            ],
            options={
                'db_table': '"comun"."categoria_contacto"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='categoriacontacto',
            index=models.Index(fields=['id'], name='categoria_c_id_286cdb_idx'),
        ),
    ]
