# Generated by Django 4.0.4 on 2022-09-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0061_categoriacontacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCategoriaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_grup', models.CharField(max_length=200, verbose_name='Descripcion del Grupo de la Categoria del Contacto')),
                ('codi_ctco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CategoriaContacto', to='asiam.categoriacontacto')),
            ],
            options={
                'db_table': '"comun"."grupo_categoria_contacto"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='grupocategoriacontacto',
            index=models.Index(fields=['id'], name='grupo_categ_id_fa1083_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grupocategoriacontacto',
            unique_together={('desc_grup', 'codi_ctco')},
        ),
    ]
