# Generated by Django 4.0.4 on 2022-09-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0062_grupocategoriacontacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_cont', models.CharField(max_length=200, verbose_name='Descripcion del Contacto')),
                ('codi_acci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_accionista_codi_acci', to='asiam.accionista')),
                ('codi_clie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_cliente_codi_clie', to='asiam.cliente')),
                ('codi_grco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GrupoCategoriaContacto', to='asiam.grupocategoriacontacto')),
                ('codi_juri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_juridica_codi_juri', to='asiam.juridica')),
                ('codi_natu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_natural_codi_natu', to='asiam.natural')),
                ('codi_prov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_proveedor_codi_prov', to='asiam.proveedor')),
                ('codi_vend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_vendedor_codi_vend', to='asiam.vendedor')),
            ],
            options={
                'db_table': '"comun"."contacto"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['id'], name='contacto_id_9d8984_idx'),
        ),
    ]
