# Generated by Django 4.0.4 on 2022-09-16 12:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0063_contacto_contacto_contacto_id_9d8984_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='location_clie',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
