# Generated by Django 4.0.4 on 2022-10-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0064_cliente_location_clie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codi_vend',
        ),
    ]
