# Generated by Django 4.0.4 on 2022-10-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0065_remove_cliente_codi_vend'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruta_detalle_vendedor_cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='asiam.rutadetallevendedor'),
        ),
    ]
