# Generated by Django 4.0.4 on 2022-10-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0066_cliente_ruta_detalle_vendedor_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ruta_detalle_vendedor_cliente',
        ),
    ]
