# Generated by Django 4.0.4 on 2022-10-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0067_remove_cliente_ruta_detalle_vendedor_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruta_detalle_vendedor_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asiam.rutadetallevendedor'),
        ),
    ]
