# Generated by Django 4.0.4 on 2022-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0069_cliente_ptor_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='nomb_sect',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre del Sector'),
        ),
    ]
