# Generated by Django 4.0.4 on 2022-10-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0070_alter_sector_nomb_sect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='nomb_sect',
        ),
    ]
