# Generated by Django 4.0.4 on 2022-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0071_remove_sector_nomb_sect'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='nomb_sect',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre del Sector'),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('nomb_sect', 'codi_ciud')},
        ),
    ]
