# Generated by Django 4.0.4 on 2022-10-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0072_sector_nomb_sect_alter_sector_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural',
            name='fipe_natu',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Firma Persona del Cliente'),
        ),
        migrations.AddField(
            model_name='natural',
            name='razo_natu',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Razon Socila del Cliente'),
        ),
    ]
