# Generated by Django 4.1.2 on 2023-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0073_natural_fipe_natu_natural_razo_natu'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='orde_zona',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordenamiento de la Zona'),
        ),
    ]
