# Generated by Django 4.1.2 on 2023-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0074_zona_orde_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('nomb_tabl', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre de la Tabla')),
                ('nomb_esqu', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre del Esquema')),
            ],
            options={
                'db_table': '"empr"."configuracion_tabla"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='configuraciontabla',
            index=models.Index(fields=['id'], name='configuraci_id_236f34_idx'),
        ),
    ]
