# Generated by Django 4.1.2 on 2023-07-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0075_configuraciontabla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBusquedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('nomb_camp', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre del Campo')),
                ('titu_camp', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Titulo del Campo')),
                ('busc_camp', models.BooleanField(blank=True, default=False, null=True, verbose_name='Permite realizar busquedad por el Campo')),
                ('orde_camp', models.BooleanField(blank=True, default=False, null=True, verbose_name='Permite ordenar por el Campo')),
                ('codi_tabl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciontabla.codi_tabl+', to='asiam.configuraciontabla')),
            ],
            options={
                'db_table': '"empr"."configuracion_busquedad"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='configuracionbusquedad',
            index=models.Index(fields=['id'], name='configuraci_id_e81a1c_idx'),
        ),
    ]
