# Generated by Django 4.1.2 on 2023-09-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0076_configuracionbusquedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='codi_pais',
            field=models.ForeignKey(default='234', on_delete=django.db.models.deletion.CASCADE, related_name='Pais.codi_pais+', to='asiam.pais'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='simb_mone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Simbolo de la Moneda'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='desc_mone',
            field=models.CharField(default='', max_length=120, unique=True, verbose_name='Descripcion de la Moneda'),
        ),
    ]
