# Generated by Django 4.1.2 on 2023-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0077_moneda_codi_pais_moneda_simb_mone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_fopa', models.CharField(blank=True, default='', max_length=120, null=True, unique=True, verbose_name='Descripcion de la Forma de Pago')),
            ],
            options={
                'db_table': '"comun"."forma_pago"',
                'ordering': ['desc_fopa'],
            },
        ),
        migrations.AddIndex(
            model_name='formapago',
            index=models.Index(fields=['id'], name='forma_pago_id_5c5671_idx'),
        ),
    ]
