# Generated by Django 4.1.2 on 2023-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0078_formapago_formapago_forma_pago_id_5c5671_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_tipe', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion del Tipo de Pedido')),
                ('orde_tipe', models.IntegerField(verbose_name='Orden del Tipo de Pedido')),
            ],
            options={
                'db_table': '"empr"."pedido_tipo"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidotipo',
            index=models.Index(fields=['id'], name='pedido_tipo_id_c90d11_idx'),
        ),
    ]
