# Generated by Django 4.1.2 on 2023-09-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0079_pedidotipo_pedidotipo_pedido_tipo_id_c90d11_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_esta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion del Estatus del Pedido')),
                ('orde_esta', models.IntegerField(verbose_name='Orden del Estatus del Pedido')),
            ],
            options={
                'db_table': '"empr"."pedido_estatus"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidoestatus',
            index=models.Index(fields=['id'], name='pedido_esta_id_d5934a_idx'),
        ),
    ]
