# Generated by Django 4.1.2 on 2023-09-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0080_pedidoestatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('fech_pedi', models.DateField(blank=True, null=True, verbose_name='Fecha de creacion del Pedido')),
                ('feim_pedi', models.DateField(blank=True, null=True, verbose_name='Fecha de Impresion del Pedido')),
                ('fede_pedi', models.DateField(blank=True, null=True, verbose_name='Fecha de Despacho del Pedido')),
                ('feve_pedi', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento del Pedido')),
                ('mont_pedi', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto del Pedido sin Descuento')),
                ('desc_pedi', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto del Descuento del Pedido')),
                ('tota_pedi', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto Total del Pedido')),
                ('obse_pedi', models.TextField(verbose_name='Observaciones del Pedido')),
                ('orig_pedi', models.TextField(verbose_name='Origen de donde fue creado el Pedido')),
                ('codi_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente.codi_clie+', to='asiam.cliente')),
                ('codi_espe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoEstatus.codi_espe+', to='asiam.pedidoestatus')),
                ('codi_mone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Moneda.codi_mone+', to='asiam.moneda')),
                ('codi_tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoTipo.codi_tipe+', to='asiam.pedidotipo')),
            ],
            options={
                'db_table': '"empr"."pedido"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['id'], name='pedido_id_bcb28b_idx'),
        ),
    ]
