# Generated by Django 4.1.2 on 2023-09-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0081_pedido_pedido_pedido_id_bcb28b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('cant_pede', models.IntegerField(verbose_name='Cantidad del Pedido Detalle')),
                ('prec_pede', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Precio del Articulo del Pedido Detalle')),
                ('desc_pede', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Descuento del Articulo del Pedido Detalle')),
                ('moto_pede', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto Total del Pedido Detalle')),
                ('codi_arti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Articulo.codi_arti+', to='asiam.articulo')),
                ('codi_pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedido.codi_pedi+', to='asiam.pedido')),
            ],
            options={
                'db_table': '"empr"."pedido_detalle"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidodetalle',
            index=models.Index(fields=['id'], name='pedido_deta_id_26cdbd_idx'),
        ),
    ]
