# Generated by Django 4.1.2 on 2023-09-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0082_pedidodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('mont_fopa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto de la Forma de Pago')),
                ('foto_fopa', models.JSONField(blank=True, null=True, verbose_name='Foto del Cliente')),
                ('obse_fopa', models.TextField(verbose_name='Observaciones de la Forma de Pago')),
                ('codi_esta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPago.codi_esta+', to='asiam.pedidoestatus')),
                ('codi_fopa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPago.codi_fopa+', to='asiam.formapago')),
                ('codi_mone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPago.codi_mone+', to='asiam.moneda')),
                ('codi_pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPago.codi_pedi+', to='asiam.pedido')),
            ],
            options={
                'db_table': '"empr"."pedido_pago_detalle"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidopagodetalle',
            index=models.Index(fields=['id'], name='pedido_pago_id_318294_idx'),
        ),
    ]
