# Generated by Django 4.1.2 on 2023-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0083_pedidopagodetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='codi_mone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Codigo de la Moneda'),
        ),
    ]
