# Generated by Django 4.1.2 on 2023-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0084_moneda_codi_mone'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='orde_fopa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden de la Forma de Pago'),
        ),
    ]
