# Generated by Django 4.1.2 on 2023-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0085_formapago_orde_fopa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='foto_pedi',
            field=models.JSONField(blank=True, null=True, verbose_name='Foto del Pedido'),
        ),
    ]
