# Generated by Django 4.1.2 on 2023-09-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0086_pedido_foto_pedi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='porc_ruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Porcentaje del Descuento de la Ruta '),
        ),
    ]
