# Generated by Django 4.1.3 on 2023-10-06 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asiam', '0088_pedidoseguimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_picture')),
                ('phone_number', models.CharField(blank=True, max_length=75)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"public"."profile"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['id'], name='profile_id_bc21b5_idx'),
        ),
    ]
