# Generated by Django 4.1.3 on 2023-10-10 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asiam', '0089_profile_profile_profile_id_bc21b5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codi_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PedidoUser.codi_user+', to=settings.AUTH_USER_MODEL),
        ),
    ]
