# Generated by Django 4.1.3 on 2023-10-10 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asiam', '0090_pedido_codi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoseguimiento',
            name='codi_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPago.codi_user+', to=settings.AUTH_USER_MODEL),
        ),
    ]
