# Generated by Django 4.1.3 on 2023-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0091_alter_pedidoseguimiento_codi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopagodetalle',
            name='fech_fopa',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pedidopagodetalle',
            name='foto_fopa',
            field=models.JSONField(blank=True, null=True, verbose_name='Foto del Pago'),
        ),
        migrations.AlterField(
            model_name='pedidopagodetalle',
            name='mont_fopa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto del Pago'),
        ),
        migrations.AlterField(
            model_name='pedidopagodetalle',
            name='obse_fopa',
            field=models.TextField(verbose_name='Observaciones del Pago'),
        ),
    ]
