# Generated by Django 4.1.3 on 2023-10-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0092_pedidopagodetalle_fech_fopa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidopagodetalle',
            old_name='fech_fopa',
            new_name='fech_page',
        ),
        migrations.RenameField(
            model_name='pedidopagodetalle',
            old_name='foto_fopa',
            new_name='foto_pade',
        ),
        migrations.RenameField(
            model_name='pedidopagodetalle',
            old_name='mont_fopa',
            new_name='mont_pade',
        ),
        migrations.RenameField(
            model_name='pedidopagodetalle',
            old_name='obse_fopa',
            new_name='obse_pade',
        ),
    ]
