# Generated by Django 4.1.3 on 2023-10-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0093_rename_fech_fopa_pedidopagodetalle_fech_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_banc', models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Nombre del Banco')),
                ('logo_banc', models.JSONField(blank=True, null=True, verbose_name='Foto del Pago')),
            ],
            options={
                'db_table': '"comun"."banco"',
                'ordering': ['desc_banc'],
            },
        ),
        migrations.AddIndex(
            model_name='banco',
            index=models.Index(fields=['id'], name='banco_id_7cb06a_idx'),
        ),
    ]
