# Generated by Django 4.1.3 on 2023-10-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0094_banco_banco_banco_id_7cb06a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('ncta_cuen', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Numero de Cuenta')),
                ('fape_cuen', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion de la Cuenta')),
                ('tipo_cuen', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Tipo de Cuenta')),
                ('codi_banc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta.codi_banc+', to='asiam.banco')),
            ],
            options={
                'db_table': '"comun"."cuenta"',
                'ordering': ['ncta_cuen'],
            },
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['id'], name='cuenta_id_c74749_idx'),
        ),
    ]
