# Generated by Django 4.1.3 on 2023-10-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0095_cuenta_cuenta_cuenta_id_c74749_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('fech_taca', models.DateField(blank=True, null=True, verbose_name='Fecha de la Tasa de Cambio')),
                ('obse_taca', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Observaciones de la Tasa de Cmabio')),
                ('esta_tasa', models.BooleanField(blank=True, default=True, null=True, verbose_name='Tasa de Cambio Activa')),
                ('codi_mone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasacambio.codi_mone+', to='asiam.moneda')),
            ],
            options={
                'db_table': '"comun"."tasa_cambio"',
                'ordering': ['fech_taca'],
            },
        ),
        migrations.AddIndex(
            model_name='tasacambio',
            index=models.Index(fields=['id'], name='tasa_cambio_id_d1b940_idx'),
        ),
    ]
