# Generated by Django 4.1.3 on 2023-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0096_tasacambio_tasacambio_tasa_cambio_id_d1b940_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='logo_banc',
            field=models.JSONField(blank=True, null=True, verbose_name='Foto del Banco'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='ncta_cuen',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Numero de Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuen',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Tipo de Cuenta'),
        ),
    ]
