# Generated by Django 4.1.3 on 2023-10-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0097_alter_banco_logo_banc_alter_cuenta_ncta_cuen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='codi_banc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco.codi_banc+', to='asiam.banco'),
        ),
    ]
