# Generated by Django 4.1.3 on 2023-10-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0098_alter_cuenta_codi_banc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='valo_taca',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Valor de la Tasa de Cambio'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='codi_mone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda.codi_mone+', to='asiam.moneda'),
        ),
    ]
