# Generated by Django 4.1.3 on 2023-10-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0099_tasacambio_valo_taca_alter_tasacambio_codi_mone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasacambio',
            name='esta_tasa',
        ),
    ]
