# Generated by Django 4.1.3 on 2023-10-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0100_remove_tasacambio_esta_tasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
