# Generated by Django 4.1.3 on 2023-10-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0102_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='porc_ruta',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=7, verbose_name='Porcentaje del Descuento de la Ruta '),
        ),
    ]
