# Generated by Django 4.1.3 on 2023-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0103_alter_ruta_porc_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nomb_ciud',
            field=models.CharField(default='', max_length=200, verbose_name='nomb_ciud'),
        ),
        migrations.RunSQL('ALTER TABLE comun.ciudad DROP CONSTRAINT ciudad_nomb_ciud_key'),
    ]
