# Generated by Django 4.1.3 on 2023-10-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0104_alter_ciudad_nomb_ciud'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nufa_pedi',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Numero de Factura del Pedido'),
        ),
    ]
