# Generated by Django 4.1.3 on 2023-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0107_pedidoseguimiento_codi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mopo_pedi',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=7, null=True, verbose_name='Monto Porcentaje del Descuento del Pronto Pago Pedido'),
        ),
    ]
