# Generated by Django 4.1.3 on 2023-11-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0109_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codi_arti',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Codigo del Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ppre_arti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Porcentaje Preferido Por Articulo'),
        ),
    ]
