# Generated by Django 4.1.3 on 2023-11-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0110_alter_articulo_codi_arti_alter_articulo_ppre_arti'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='exis_arti',
            field=models.IntegerField(blank=True, null=True, verbose_name='Existencia del Articulo'),
        ),
    ]
