# Generated by Django 4.1.3 on 2023-12-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0111_articulo_exis_arti'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('desc_mens', models.CharField(blank=True, max_length=254, null=True, verbose_name='Descripcion del Mensaje')),
                ('pred_mens', models.BooleanField(blank=True, default=False, null=True, verbose_name='Predeterminado Mensaje')),
                ('codi_tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MensajeTipo.codi_tipe+', to='asiam.pedidotipo')),
            ],
            options={
                'db_table': '"empr"."pedido_mensaje"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidomensaje',
            index=models.Index(fields=['id'], name='pedido_mens_id_f92fda_idx'),
        ),
    ]
