# Generated by Django 4.1.3 on 2023-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0112_pedidomensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ppre_arti',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Porcentaje Preferido Por Articulo'),
        ),
    ]
