# Generated by Django 4.1.3 on 2024-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0114_alter_articulo_por1_arti_alter_articulo_por2_arti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='fech_taca',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la Tasa de Cambio'),
        ),
    ]
