# Generated by Django 4.1.3 on 2024-01-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0115_alter_tasacambio_fech_taca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoPagoDetalle',
        ),
    ]
