# Generated by Django 4.1.3 on 2024-01-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0116_delete_pedidopagodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('fein_cobr', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso del Cobrador')),
                ('foto_cobr', models.JSONField(blank=True, null=True, verbose_name='Foto del Cobrador')),
                ('lice_cobr', models.BooleanField(blank=True, default=False, null=True, verbose_name='Posee Licencia de Conducir el Cobrador')),
                ('feli_cobr', models.DateField(blank=True, null=True, verbose_name='Fecha de Expedicion de la Licencia del Cobrador')),
                ('fvli_cobr', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento de la Licencia del Cobrador')),
                ('tili_cobr', models.IntegerField(blank=True, default=1, null=True, verbose_name='Tipo de Licencia del Cobrador')),
                ('codi_natu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrador.codi_natu+', to='asiam.natural')),
            ],
            options={
                'db_table': '"empr"."cobrador"',
                'ordering': ['codi_natu'],
            },
        ),
        migrations.AddIndex(
            model_name='cobrador',
            index=models.Index(fields=['id'], name='cobrador_id_a20ca2_idx'),
        ),
    ]
