# Generated by Django 4.1.3 on 2024-01-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0117_cobrador_cobrador_cobrador_id_a20ca2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('mont_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto del Pago')),
                ('obse_pago', models.TextField(blank=True, null=True, verbose_name='Observaciones del Pago')),
                ('fech_pago', models.DateField(blank=True, null=True, verbose_name='Fecha del Pago')),
                ('topa_pago', models.BooleanField(blank=True, default=False, null=True, verbose_name='Total Abono del Pago')),
                ('codi_esta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPago.codi_esta+', to='asiam.pedidoestatus')),
                ('codi_pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPago.codi_pedi+', to='asiam.pedido')),
            ],
            options={
                'db_table': '"empr"."pedido_pago"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidopago',
            index=models.Index(fields=['id'], name='pedido_pago_id_94dc83_idx'),
        ),
    ]
