# Generated by Django 4.1.3 on 2024-01-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0118_pedidopago_pedidopago_pedido_pago_id_94dc83_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('mont_pade', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Monto del Pago')),
                ('foto_pade', models.JSONField(blank=True, null=True, verbose_name='Foto del Pago')),
                ('obse_pade', models.TextField(blank=True, null=True, verbose_name='Observaciones del Detalle Pago')),
                ('codi_cobr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPagoDetalle.codi_cobr+', to='asiam.cobrador')),
                ('codi_esta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPagoDetalle.codi_esta+', to='asiam.pedidoestatus')),
                ('codi_fopa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPagoDetalle.codi_fopa+', to='asiam.formapago')),
                ('codi_mone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPagoDetalle.codi_mone+', to='asiam.moneda')),
                ('codi_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPagoDetalle.codi_pago+', to='asiam.pedidopago')),
                ('codi_tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoPagoDetalle.codi_tasa+', to='asiam.tasacambio')),
            ],
            options={
                'db_table': '"empr"."pedido_pago_detalle"',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidopagodetalle',
            index=models.Index(fields=['id'], name='pedido_pago_id_318294_idx'),
        ),
    ]
