# Generated by Django 4.1.3 on 2024-02-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0121_moneda_orde_mone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonedaDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ttus', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('tipo_deno', models.CharField(blank=True, choices=[('1', 'Billete'), ('2', 'Moneda')], max_length=50, verbose_name='Tipo de la Denominacion Billete-Moneda')),
                ('nomb_deno', models.CharField(default='', max_length=120, unique=True, verbose_name='Nombre de la Denominacion')),
                ('valo_deno', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor de la Denominacion')),
                ('foto_deno', models.JSONField(blank=True, null=True, verbose_name='Foto de la Denominacion')),
                ('orde_deno', models.IntegerField(default=1, verbose_name='Indice de Ordenamiento de la Denominacion')),
                ('codi_mone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedaDenominacion.codi_mone+', to='asiam.moneda')),
            ],
            options={
                'db_table': '"comun"."moneda_denominacion"',
                'ordering': ['nomb_deno'],
            },
        ),
        migrations.AddIndex(
            model_name='monedadenominacion',
            index=models.Index(fields=['id'], name='moneda_deno_id_5a75e2_idx'),
        ),
    ]
