# Generated by Django 4.1.3 on 2024-02-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0123_tasacambio_tipo_taca'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='codi_mone_to',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='moneda.codi_mone_to+', to='asiam.moneda'),
        ),
    ]
