# Generated by Django 4.1.3 on 2024-03-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0124_tasacambio_codi_mone_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codi_clie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente.codi_clie+', to='asiam.cliente'),
        ),
    ]
