# Generated by Django 4.1.3 on 2024-06-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0125_alter_pedido_codi_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codi_clie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_cliente_codigo', to='asiam.cliente'),
        ),
    ]
