# Generated by Django 4.1.3 on 2024-07-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0127_alter_pedido_codi_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codi_natu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_natural_code', to='asiam.natural'),
        ),
    ]
