# Generated by Django 4.1.3 on 2024-07-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0128_alter_cliente_codi_natu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id']},
        ),
    ]
