# Generated by Django 4.1.3 on 2024-07-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0129_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['codi_natu', 'codi_juri']},
        ),
    ]
