# Generated by Django 4.1.3 on 2024-07-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0130_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-id']},
        ),
    ]
