# Generated by Django 5.0.6 on 2024-11-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiam', '0131_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='codi_natu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_natural_code', to='asiam.natural'),
        ),
    ]
